---
project: "A Linear Regression"
author: "Andre-Ignace Ghonda Lukoki"
url: www.andreghonda.com
contact: contact@andreghonda.com
date: !!timestamp 2024-05-20
description: README.md
---
R:
  version: "4.3.1"
  path: R/regress.r
  history: .Rhistory
  data: .Rdata
  completed: !!bool true
---
julia:
  version: "1.10.3"
  path: Julia/regress.jl
  packages:
    - CSV
    - DataFrames
    - Distributions
    - GLM
    - HypothesisTests
    - Plots
    - LinearAlgebra
    - Random
    - Statistics
  completed: !!bool false
...
